### ISSUE TITLE
Schema Version: No version number found. Did you forget a commit during installation?

### ISSUE THREAD

**Issue by musakocak** [bitnami/bitnami-docker-reportserverenterprise#1]
Hello, I install reportserver on docker but it is not running. I see  the error below. Please help me, thanks. 

ReportServer encountered an error while validating its environment. Please check the server log files for additional information.

Version: RS3.1.2-6022 2020-04-01-15-17-05
Code Version: 2020-04-01-14-55-32
Java Version: BellSoft OpenJDK 64-Bit Server VM 11.0.7+10-LTS (11)
VM Args: --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED -Djava.util.logging.config.file=/opt/bitnami/tomcat/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Djava.awt.headless=true -Xmx4g -XX:+UseConcMarkSweepGC -XX:MaxPermSize=512M -Dfile.encoding=UTF8 -Drs.configdir=/opt/bitnami/reportserver/conf -Djdk.tls.ephemeralDHKeySize=2048 -Djava.protocol.handler.pkgs=org.apache.catalina.webresources -Dorg.apache.catalina.security.SecurityListener.UMASK=0027 -Dignore.endorsed.dirs= -Dcatalina.base=/opt/bitnami/tomcat -Dcatalina.home=/opt/bitnami/tomcat -Djava.io.tmpdir=/opt/bitnami/tomcat/temp
rs.configdir: /opt/bitnami/reportserver/conf (OK)

### DB Config ###
hibernate.dialect: net.datenwerke.rs.utils.hibernate.MySQL5Dialect (OK)
hibernate.connection.driver_class: com.mysql.jdbc.Driver (OK)
hibernate.connection.url: jdbc:mysql://mariadb:3306/bitnami_reportserver (OK)
hibernate.connection.username: bn_reportserver
hibernate.connection.password: 
hibernate.default_schema: 

Connection Test: OK
Schema Version: No version number found. Did you forget a commit during installation?

**Comment by andresbono** [comment]
Hi @musakocak, can you tell us how are you launching the containers? Are you using `docker run`? Are you using `docker-compose`?

**Comment by musakocak** [comment]
Hi, @andresbono, I'm using "docker-compose". Thanks.

**Comment by andresbono** [comment]
We couldn't reproduce your issue just by running `docker-compose up`. We tested it on:

```
docker-compose version 1.25.0
Docker version 19.03.8
OS: Linux, Ubuntu 18.04.4 LTS
```

Can you think of any peculiarities of your environment that could make it fail?

**Comment by musakocak** [comment]
After OS and package update, I reinstalled the image and it worked fine. Thank you for your help.

OS: Centos7
docker-compose version: 3.7.3
Docker version: 19.03.8
