### ISSUE TITLE
Environment Variable for SMTP are incorrect.

### ISSUE THREAD

**Issue by TheDigitalEagle** [bitnami/bitnami-docker-reportserverenterprise#2]
Environment Variable for SMTP are incorrect. You will get NULL for SMTP in ReportServer if you follow the guide in the ReadMe.

**Comment by javsalgar** [comment]
Hi,

Checking the logs I could see that there's an issue indeed

```
reportserverenterprise_1  | 13:47:34.974 WARN  n.d.rs.installation.InitConfigTask - Failed to set property during initialization: cfg.mail.mail_cf.smtp.tls.require
reportserverenterprise_1  | [Fatal Error] :5:4: The string "--" is not permitted within comments.
reportserverenterprise_1  | 13:47:35.000 WARN  n.d.r.c.s.c.ConfigServiceImpl - Configfile mail/mail.cf could not be loaded. Default values are in effect.
reportserverenterprise_1  | 13:47:35.000 WARN  n.d.rs.installation.InitConfigTask - Failed to set property during initialization: cfg.mail.mail_cf.smtp.port
reportserverenterprise_1  | 13:47:35.014 INFO  n.d.r.p.s.BsiPasswordPolicyServiceImpl - Password policy not active: Could not find config for security/passwordpolicy.cf
reportserverenterprise_1  | [Fatal Error] :5:4: The string "--" is not permitted within comments.
reportserverenterprise_1  | 13:47:35.035 WARN  n.d.r.c.s.c.ConfigServiceImpl - Configfile mail/mail.cf could not be loaded. Default values are in effect.
reportserverenterprise_1  | 13:47:35.035 WARN  n.d.rs.installation.InitConfigTask - Failed to set property during initialization: cfg.mail.mail_cf.smtp.host
reportserverenterprise_1  | [Fatal Error] :5:4: The string "--" is not permitted within comments.
reportserverenterprise_1  | 13:47:35.048 WARN  n.d.r.c.s.c.ConfigServiceImpl - Configfile mail/mail.cf could not be loaded. Default values are in effect.
reportserverenterprise_1  | 13:47:35.048 WARN  n.d.rs.installation.InitConfigTask - Failed to set property during initialization: cfg.mail.mail_cf.smtp.password
reportserverenterprise_1  | [Fatal Error] :5:4: The string "--" is not permitted within comments.
reportserverenterprise_1  | 13:47:35.068 WARN  n.d.r.c.s.c.ConfigServiceImpl - Configfile mail/mail.cf could not be loaded. Default values are in effect.
reportserverenterprise_1  | 13:47:35.068 WARN  n.d.rs.installation.InitConfigTask - Failed to set property during initialization: cfg.mail.mail_cf.smtp.username
```

I will open a task to check it. Thank you for reporting!

**Comment by TheDigitalEagle** [comment]
Thanks javsalgar! 
Would there happen to be any suggested way we might  be able to work around this better? We are implementing the enterprise version in production soon and the bitnami edition was pretty nice minus the lack of working SMTP. We've been digging around the bash to see if we can resolve on our end but not having much luck finding the generate rsinit.properties where the mail/mail.cf would be generated from.

**Comment by javsalgar** [comment]
I believe that another option would be changing the settings directly in the database, but that's something we would need to check how to do.

**Comment by carrodher** [comment]
Hi, unfortunately, if the issue is not solved in recent versions means the task is still on our backlog and there are no plans to work on it in the short/middle term.

In the same way, please, [note the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-reportserverenterprise#community-supported-solution) since this asset was marked as a “Community supported solution”.

At this point, the best option to fix any issue or add a new feature is to contribute create a PR; the Bitnami team will be happy to review it and provide feedback.
